### ISSUE TITLE
Missing all Go lang standard library packages

### ISSUE THREAD

**Issue by xnuinside** [google/deps.dev#101] opened 2024-07-24 13:52 UTC
Hello! 

Thanks for the project, but there is an issue:
https://pkg.go.dev/std - all those packages (from standard library) are missing on https://deps.dev/.

**Comment by sarnesjo-google** [comment] 2024-07-24 22:02
Duplicate of #86

**Closed by sarnesjo-google** 2024-07-24 22:02 UTC

**Comment by xnuinside** [comment] 2024-07-25 11:24
@sarnesjo-google sorry for duplicate) thanks!
